### ISSUE TITLE
TypeError shown in logs

### ISSUE THREAD

**Issue by saulmm** [eBay/firebase-remote-config-monitor#2]
Tried to enable this RC monitor on our project. Seems to not work and there are some failed logs in CF logs:

![image](https://user-images.githubusercontent.com/3531999/56653341-c69b5000-668d-11e9-90e5-79621a1cfb40.png)

> error encountered: TypeError: Cannot read property 'length' of undefined

**Comment by frindly** [comment]
Hey Saul,

Was this the 1st time the function run or was it working and then failed?
Was the execution kicked off from the trigger (i.e. you changed a RC
parameter or condition and published) or did you manually invoke the
function?

Thanks,

Jake

**Comment by saulmm** [comment]
It was the first time. I was trying the monitor to trigger after
switching/adding some values on RC. Anyway it started to work suddenly
after a few hours, so I guess it's fine :)

**Comment by saulmm** [comment]
Actually, these are the logs in the now happy scenario:

![image](https://user-images.githubusercontent.com/3531999/56728310-cdd86180-6752-11e9-9d66-c2b0626c3cc6.png)

Thanks!

**Comment by frindly** [comment]
Hmm... a heisenbug, always the best.  Well i'm glad it working for you
now!  Please let me know if it misbehaves again :)

**Comment by rodrigovallades** [comment]
I'm getting this in all executions, it has never worked for me :(

Executions are being kicked off from the trigger.

<img width="1269" alt="Screen Shot 2020-01-31 at 16 26 55" src="https://user-images.githubusercontent.com/6432271/73568144-949df200-4446-11ea-86cf-788ac307f1ec.png">

Any ideas?

**Comment by frindly** [comment]
Is it possible you have 0 conditions or 0 parameters setup?

**Comment by rodrigovallades** [comment]
Hey @frindly , I do have parameters. I did have 0 conditions, but I just created one and the error persists still. :(

<img width="963" alt="Screen Shot 2020-02-01 at 22 02 31" src="https://user-images.githubusercontent.com/6432271/73601348-a6fb5700-453e-11ea-8d6a-c7f1cdcf294f.png">

**Comment by alex-vasenin** [comment]
I had those errors because I have zero conditions. Solved it by removing call to `diffConditions(...)` in `rc_config_diff.js` (and returning only `paramDiffs`). Those kind of edge cases should be checked by default.
